### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by jsraadt** [JestonBlu/RobinHood#100]
https://github.com/JestonBlu/RobinHood/blob/9d1046ffec1767afd5ea06194cee708a462ac238/R/api_login.R#L15

I'm concerned about security. I'm not shabby at R, but interacting with API is newer to me. That's why I reference line 15 from the `api_login` function, which I understand the main "gateway" between R and Robinhood. Why is the `api_client_id` object some static string of characters?

**Comment by JestonBlu** [comment]
It's a fixed string used by the Robin Hood app is my understanding. As far as I know all software packages using the API have the same fixed string.
