### ISSUE TITLE
Fractional Share Trading

### ISSUE THREAD

**Issue by tonytrevisan** [JestonBlu/RobinHood#101]
Hello,

Is there any interest in building the fractional share trading ability into the Place Order function?

**Comment by JestonBlu** [comment]
Yes, i will look into that. I think you have to be account eligible for it to work because I dont think its built in site wide yet, but i will check that out and see.

**Comment by ttrevisan18** [comment]
I am fairly certain it's platform wide at this point. What API documentation are you consulting to build out these functions?

**Comment by JestonBlu** [comment]
There is no API guide that is published. I learned some of the endpoints from a couple other rh rpos on GitHub. Other than that I used the browser dev tools to figure out the API.

**Comment by tonytrevisan** [comment]
I forgot to mention, I have been trading fractional shares with the place order function. The one change I made was to comment out the “quantity < 1” stop error so that I can less than 1. Other than that the function works for fractional.

**Comment by JestonBlu** [comment]
this will be fixed in the next release, thanks

**Comment by tonytrevisan** [comment]
Hi,

I looked at the place_order function and saw that the line "if (quantity < 1) stop("quantity must be > 0")" is still present. I think this should be removed to allow for fractional shares less than 1. For example, $100 of SPY would not be a full share.

**Comment by JestonBlu** [comment]
Sorry i thought i fixed that. Its done and pushed to github.

**Comment by willywonka0** [comment]
where can it be found on GitHub? (can you post the code like above)
