### ISSUE TITLE
More detailed historical data

### ISSUE THREAD

**Issue by chuymtz** [JestonBlu/RobinHood#102]
Great package!

I was just playing with it and noticed that when using the get_historicals function, there's no option for setting the bounds or the collection times. That is, it seems to me that i only get sparse prices for a certain coin and i cant control with how much frequency i can pull my historical prices. 

In the past I've used the robin-stocks python api which just recently made upgrades to this functionality.

Thanks!

**Comment by JestonBlu** [comment]
Can you give me a reproducible example of what you are talking about?
