### ISSUE TITLE
Issue with get_positions

### ISSUE THREAD

**Issue by sanseveroj** [JestonBlu/RobinHood#103]
Whenever I use get_positions I get an error saying:

Error in handle_url(handle, url, ...) : 
  Must specify at least one of url or handle

I'm not sure if this issue is specific to me, perhaps because I have no stocks that it can't return any information?

Anyone else experiencing this?

**Comment by hisamsabounitadg** [comment]
Bump. 

Also having an issue with get_positions():

> get_positions(RH)
Error: Unknown column `shares_held_for_stock_grants` 
Run `rlang::last_error()` to see where the error occurred.

**Comment by hisamsabouni** [comment]
Bump.

Also having an issue with get_positions():

> get_positions(RH, limit = FALSE)
Error: Unknown column `shares_held_for_stock_grants` 
Run `rlang::last_error()` to see where the error occurred.

**Comment by hisamsabouni** [comment]
> Bump.
> 
> Also having an issue with get_positions():
> 
> > get_positions(RH, limit = FALSE)
> > Error: Unknown column `shares_held_for_stock_grants`
> > Run `rlang::last_error()` to see where the error occurred.

Never mind. This works fine assuming that the portfolio actually has a position. If there are no positions you will receive the error I posted.

**Comment by JestonBlu** [comment]
Sorry for the delay, i will add a task to return a message when there are no positions to display
