### ISSUE TITLE
Enable 2FA

### ISSUE THREAD

**Issue by JestonBlu** [JestonBlu/RobinHood#104]

**Comment by fouslim** [comment]
@JestonBlu thanks for the new commit

I think you forgot to pass the mfa_code argument to the api_login function in the RobinHood::RobinHood
https://github.com/JestonBlu/RobinHood/blob/2c04d1f0282e80e4773e17b8cf6b1d1a873ba08a/R/RobinHood.R#L18

again, many thanks

**Comment by JestonBlu** [comment]
Thanks, you are right, patching now.

**Comment by JestonBlu** [comment]
I pushed a change, let me know if that doesnt work.

**Comment by fouslim** [comment]
it works, thks a lot
