### ISSUE TITLE
Error in UseMethod("tbl_vars") despite the correct username and password

### ISSUE THREAD

**Issue by kpmainali** [JestonBlu/RobinHood#106]
When I try to log in with the following using my correct username and password, I get the following error message.
`RH <- RobinHood(username = "username", password = "password")
`
Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "NULL"

I do not have any escape characters in my username or password. The only character other than letter is a hyphen. Any help is appreciated.

**Comment by JestonBlu** [comment]
Could you try changing your password to remove the hiphen? Not sure if thats the problem. I tested the login function this morning and i have no issues. Also, for your username, did you pull in your full email? Ive heard some people complain that it only works with the full email address. Let me know and ill look into it further.

**Comment by kpmainali** [comment]
I have now changed the password by removing hyphen. Now all the characters are either letters or numbers. The username has full email address. Still I get the same error message.

**Comment by JestonBlu** [comment]
Okay, i havent been able to reproduce your error except when I provide an incorrect password. I am able log in fine so im not sure exactly what the issue is.

**Comment by rmcna86394** [comment]
I'm encountering the same error. Each time I execute the RobinHood function in R I receive a SMS push notification advising my login attempt was blocked and provided a security code to use to login.

**Comment by kpmainali** [comment]
I tried the function RobinHood() in Google's AI Platform as well and still got the same error. So, this error is not device specific (I use a Mac).

**Comment by sxf279** [comment]
@kpmainali did you enable "Two-Factor Authentication"? If you enabled it (Account > Settings > Security) that may be why you are getting this error.

**Comment by kpmainali** [comment]
@sxf279 I do have two-factor authentication enabled. I am not sure why two factor authentication results into this problem. I can access my Robinhood account with a python library robin_stocks in Google Colab. This requires me typing the authentication code. Whereas Colab runs on the browser, R runs in my local machine which is a MacBook Pro.
