### ISSUE TITLE
get_tickers(RH,add_fundamentals=TRUE) Error: Can't transform a data frame with duplicate names.

### ISSUE THREAD

**Issue by hamannj** [JestonBlu/RobinHood#108]
This is a GREAT package!

When trying out the get_tickers() with the add_fundamentals=TRUE, I got the following error: 

t2 <- get_tickers(RH,add_fundamentals=TRUE)
Getting stock ticker data from RobinHood.com.............COMPLETE ( 1.49 minutes)
Getting additional investment fundamentals...Error: Can't transform a data frame with duplicate names.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Can't transform a data frame with duplicate names.
Backtrace:
 1. RobinHood::get_tickers(RH, add_fundamentals = TRUE)
 4. dplyr::mutate_at(...)
 6. dplyr:::mutate.data.frame(.tbl, !!!funs)
 7. dplyr:::mutate_cols(.data, ...)
 8. DataMask$new(.data, caller_env())
 9. dplyr:::initialize(...)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Can't transform a data frame with duplicate names.
Backtrace:
    █
 1. ├─RobinHood::get_tickers(RH, add_fundamentals = TRUE)
 2. │ └─RobinHood::get_fundamentals(RH, symbols[i])
 3. │   └─`%>%`(...)
 4. └─dplyr::mutate_at(...)
 5.   ├─dplyr::mutate(.tbl, !!!funs)
 6.   └─dplyr:::mutate.data.frame(.tbl, !!!funs)
 7.     └─dplyr:::mutate_cols(.data, ...)
 8.       └─DataMask$new(.data, caller_env())
 9.         └─dplyr:::initialize(...)
> 

That's as much diagnostic materials as I have. Am I missing something?

**Comment by JestonBlu** [comment]
@hamannj should be fixed now on github, ill probably fix a few more bugs before pushing another CRAN update, i just submitted 1.5 last night
