### ISSUE TITLE
Error in dta_cost[[i]]: attempt to select less than one element in integerOneIndex

### ISSUE THREAD

**Issue by fouslim** [JestonBlu/RobinHood#110]
I get the error below when trying to call the function get_positions_crypto
`get_positions_crypto(RH = RH)`
> Error in dta_cost[[i]] :
   attempt to select less than one element in integerOneIndex 
  
`traceback()`
> 2: api_positions_crypto(RH)
 1: get_positions_crypto(RH = RH)

if think it is caused when trying to fetch the cost_bases (in my case I own one cryptocurrency)
https://github.com/JestonBlu/RobinHood/blob/1714e7453fe60a9952ef0813848557f1e87d1a3e/R/api_positions_crypto.R#L40
so it tries to fetch dta_cost[[0]] which throws the error above.
 
the fix is not to loop from `1:(length(dta_cost) - 1)` but instead from `1:length(dta_cost)`

**Comment by JestonBlu** [comment]
thanks for the feedback, ill take a look

**Comment by JestonBlu** [comment]
I dont remember why i had that -1 in there... i guess in my case i have 3 positions, but cost basis returns a length of 4 with no data so i must have tried to trim that out, but i just tried it with the -1 gone and it worked the same. I am pushing a change to github, let me know if you are still having trouble.

**Comment by fouslim** [comment]
That fixed the error. Thanks.
