### ISSUE TITLE
api_marketdata error when converting json to data.frame 

### ISSUE THREAD

**Issue by fouslim** [JestonBlu/RobinHood#111]
I get the error bellow when calling the function get_positions_options:
`> get_positions_options(RH = RH)`
 `Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
   arguments imply differing number of rows: 1, 0`
`>traceback()`
` 5: do.call(data.frame, c(x, alis))` 
` 4: as.data.frame.list(dta)`
 `3: as.data.frame(dta)`
 `2: api_marketdata(RH, i)`
 `1: get_positions_options(RH = RH)`

below is a call to reproducible error:
`> RobinHood::api_marketdata(RH, "4ba07b02-638f-4b7e-a907-58bd592b1a79")`
`Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
   arguments imply differing number of rows: 1, 0`

The error seems to come from the lines below in RobinHood::api_marketdata
 `dta <- mod_json(dta, "fromJSON")`
  `if (type == "instrument_id") {`
`        dta <- as.data.frame(dta)`
`    }`

it seems that some of the fields are NULL for that option which cause the error when converting the JSON output to as.dataframe:
`> dta[sapply(dta, FUN = is.null)]`
`$chance_of_profit_long`
` NULL`
  
` $chance_of_profit_short`
` NULL`

the fix I found is to convert NULL to NA before converting the JSON list to a data.frame in RobinHood::api_marketdata (at line 30)
 `dta <- mod_json(dta, "fromJSON")`
`dta[sapply(dta, FUN = is.null)] <- NA`
  `if (type == "instrument_id") {`
`        dta <- as.data.frame(dta)`
`    }`

**Comment by JestonBlu** [comment]
thanks for the feedback i will look at this shortly

**Comment by JestonBlu** [comment]
should be fixed now, thanks for the tip
