### ISSUE TITLE
get_tag not working with some popular lists

### ISSUE THREAD

**Issue by brndngrhm** [JestonBlu/RobinHood#112]
this package is great, so glad i discovered it! 

I noticed that `get_tag()` doesn't seem to work with all the popular lists on Robinhood. The documentation indicates it works with hyphenated RH tags.

the documentation example works: 
`get_tag(RH, 100-most-popular)`

and it works with some other tags, like
`get_tag(RH, healthcare)`

but other popular RH tags return `NULL`, for example:
`get_tag(RH, crypto)`

Is it possible to for this  function to work with all  tags? Thanks!

(Also let me know if i've misunderstood the `get_tag()` documentation)

**Comment by JestonBlu** [comment]
@brndngrhm im getting your same results. I will look into seeing if i can build out a list of all of the tags.

**Comment by JestonBlu** [comment]
I spent some time looking into it and I was able to figure out a lot of the tags, but not cryptocurrency. It seems to be pretty consistent with the tag as its displayed on the website, except for a few. If you figure some more out let me know. Ive added the ones I could find to the docs. Also pasted below

```r
# Known Tags
#
#   top-movers
#   etf
#   100-most-popular
#   mutual-fund
#   finance
#   cap-weighted
#   investment-trust-or-fund
#   upcoming-earnings
#   china
#   healthcare
#   technology
#   hospitality
#   banking
#   automotive
#   agriculture
#   energy
#   finance
#   entertainment
```
