### ISSUE TITLE
List of all watchlists

### ISSUE THREAD

**Issue by gustavo-hideo** [JestonBlu/RobinHood#113]
The function watchlist(RH, action='get') is only returning 'Default', instead of a list of my watchlists.

**Comment by JestonBlu** [comment]
@gustavo-hideo the api did change so i had to do a little re-engineering. I think i need to rewrite the watchlist function so im going to do a new branch for that. In the meantime i have pushed a patch that will let you get your watchlists and then also retrieve the symbols for a particular watchlist. 

Ill expand the functionality in the pull request. Hopefully ill be able to do it all this weekend. Let me know if you have other issues. Ill leave this open until i finish the pull request.

```r
> watchlist(RH, action = "get")
[1] "Other"         "My First List"
> watchlist(RH, action = "get", watchlist = "My First List")
[1] "CAT" "AM" 
```

**Comment by gustavo-hideo** [comment]
Thank you!
