### ISSUE TITLE
get_positions_crypto()

### ISSUE THREAD

**Issue by LDleo** [JestonBlu/RobinHood#114]
Hello!
I am getting the following error on get_positions_crypto(RH)

Error in `$<-.data.frame`(`*tmp*`, "cost_bases", value = c("178.270000000000000000",  : 
  replacement has 6 rows, data has 7

Could you please help me solve the issue?

Appreciate it!

**Comment by JestonBlu** [comment]
@LDleo  I'll check it out. How many positions do you have for my reference. I'm guessing the api changed.

**Comment by LDleo** [comment]
@JestonBlu Thank you so much for your answer. It seems to be working today have no idea why. I have 6 crypto positions active now, but I used to have seven (not sure if this info helps). Please let me know if you need any other information.

**Comment by LDleo** [comment]
@JestonBlu However the values of i) quantity, ii) market_value, and iii) gain_loss do not seem to match. iv) cost_bases is matching my online account.

**Comment by JestonBlu** [comment]
@LDleo no problem. I'll verify the api works.

**Comment by LDleo** [comment]
@JestonBlu Thanks! Very helpful package by the way!

**Comment by JestonBlu** [comment]
@LDleo I believe i have addressed this. Let me know if you have more issues. Will include in my next push to CRAN, probably soon.
