### ISSUE TITLE
get_order_history_crypto()

### ISSUE THREAD

**Issue by 62keram** [JestonBlu/RobinHood#115]
Hello J,

_get_order_history_crypto()_ function does not retrieve full history. It is pulling only records from January 16, 2021 onward and not all the records. The regular stock history worked without any problems.
Not sure if others are seeing the same issue or not.

Thanks

**Comment by JestonBlu** [comment]
@62keram yeah this has been reported a couple of times. Its not really a bug, crypto is a different api than stocks and right now just pulls a default range. Ill see what I can do about increasing the time range.

**Comment by JestonBlu** [comment]
@62keram I have been looking at this and I see history for myself going back a year... im wondering if its more of a limit on the number of records it returns and i need to build in a pager function like i have with some of the other functions... can you tell me what number of records `get_order_history_crypto()` returns for you? Is it 100 by chance?

**Comment by 62keram** [comment]
@JestonBlu yes indeed, the number of records is always the same, in my case it is always 75 entries.

**Comment by JestonBlu** [comment]
@62keram this should be good to go now. Also changed the output a little to make it look a little cleaner. Let me know if you run into issues.

**Comment by 62keram** [comment]
@JestonBlu 

Did not see updated version at first on CRAN but now I installed V1.6 the record cap is no longer present. Thank you very much !
