### ISSUE TITLE
Fractional Shares Request

### ISSUE THREAD

**Issue by mfhisojs** [JestonBlu/RobinHood#121]
When attempting to buy fractional shares an error is presented like the following 
```Error in place_order(RH = RH, symbol = "ZIXI", type = "market", time_in_force = "gtc",  : 
  quantity must be > 0
```

Is there a plan to include fractional share purchasing within the `place_order()` function?

**Comment by JestonBlu** [comment]
@mfhisojs yes i have fixed this on github and the next push to CRAN will include it. I plan to submit a new version to CRAN in a day or so.

**Comment by JestonBlu** [comment]
@mfhisojs  I have submitted to CRAN, it should populate in a day or so, if you have this problem after upgrading let me know and ill reopen.

**Comment by mfhisojs** [comment]
Thank you!
