### ISSUE TITLE
Inaccurate Return from get_positions_crypto()

### ISSUE THREAD

**Issue by jrosiene** [JestonBlu/RobinHood#125]
Using get_positions_crypto(RH) returns inaccurate data.
As below.  (I definitely don't hold 1 bitcoin)
![image](https://user-images.githubusercontent.com/38916780/111923689-c0c76880-8a76-11eb-9237-90f02329cb86.png)

**Comment by JestonBlu** [comment]
@jrosiene Strange, i dont seem to be able to reproduce that error. How many bitcoin is it supposed to show? Here is mine that I just tested.

```r
> get_positions_crypto(RH)
  symbol             name    quantity market_value   mark_price cost_bases gain_loss          created_at
1    BTC          Bitcoin  0.00026476        14.98 56593.941595       1.62     13.36 2020-03-22 13:13:00
2   DOGE         Dogecoin 89.00000000         5.11     0.057447       4.39      0.72 2019-07-15 21:08:19
3    ETC Ethereum Classic 20.39003600       273.37    13.406874      89.48    183.89 2019-02-01 00:23:40
```

You arent on an older version of the package by chance? Also strange that your cost basis is 0. Can you give me any more info?

**Comment by jrosiene** [comment]
Hey Jeston,  Thanks for the quick reply.  Here I will attach my sessionInfo for you. 
![image](https://user-images.githubusercontent.com/38916780/111935157-40662f00-8a99-11eb-8852-2ff79d786ac8.png)
Indeed the cost basis is zero because I have never purchased BTC!  Also it is supposed to show about 171 DOGE, and not 2, as you saw above.  Also, if I make transactions, the return of this function never changes.  I should also note that get_positions(RH), works as expected, and returns correct values, as I will show.
![image](https://user-images.githubusercontent.com/38916780/111935309-9509aa00-8a99-11eb-936c-bca05b09a9fb.png)

What sort of information would be most helpful for you to diagnose this issue?  I will try to get you what I can.

**Comment by JestonBlu** [comment]
So you have never bought any bitcoin even through fractional trading? It looks like you are using an outdated package version. Can you upgrade and see if you are still seeing the issue?
