### ISSUE TITLE
api_contracts function is not recognised

### ISSUE THREAD

**Issue by paragemini** [JestonBlu/RobinHood#134]
After installing this package from CRAN and from Github all of the api functions seem to be unrecognizable. but all the get_functions works well? Is there any issue from my side that is creating this error?
```
d <- api_contracts(RH, chain_symbol= "TSLA", type = "call")
Error in api_contracts(RH, chain_symbol = "TSLA", type = "call") : 
  could not find function "api_contracts"
```

**Comment by JestonBlu** [comment]
The api functions are not exported in the CRAN version to keep the namespace small. The get functions are intended to be what the user executes. All get functions call one or more api functions. In the docs i have a network plot that shows how all [functions](https://jestonblu.github.io/RobinHood/articles/network_graph.html) are related.  

If you want to be able to execute the api functions for trouble shooting or just wanting to do your own thing then you can install the github version of the package. I export all functions in that version mainly for the purpose of troubleshooting.

**Comment by paragemini** [comment]
all right, thanks. Just trying to get all the options contract for all expirations. I thought the api_contract function would return all of it. Might have to dig deep. Thanks for your help!
