### ISSUE TITLE
get_positions_options: Column `updated_at` doesn't exist

### ISSUE THREAD

**Issue by fouslim** [JestonBlu/RobinHood#139]
Hi @JestonBlu,

i got an error today while calling get_positions_options
```
> get_positions_options(RH = RH)
Error: Can't subset columns that don't exist.
x Column `updated_at` doesn't exist.
```
below is the traceback:
```
2: options %>% dplyr::select(c("chain_symbol", "option_type", "state", 
       "strike_price", "average_price", "quantity", "trade_value_multiplier", 
       "last_trade_price", "current_value", "rhs_tradability", "tradability", 
       "type", "created_at", "updated_at"))
1: get_positions_options(RH = RH)
```
I'm using the RobinHood_1.6 downloaded from CRAN

I think the error is coming from line 66 of the get_positions_options.R when you do the inner_join
```
options <- dplyr::inner_join(options, option_market_data, by = "option")
```
it seems that the data.frame option_market_data also have an `updated_at` column.

The fix I found is to remove the column `updated_at` from the data.frame `option_marker_data` before the inner_join at lines 61-64: 
```
option_market_data <- option_market_data %>%
    dplyr::rename("option" = "instrument") %>%
    dplyr::mutate_at("option", as.character)  %>%
    dplyr::select(-updated_at)
```

**Comment by JestonBlu** [comment]
Thanks, I’ll check it out. Sounds like an api change.

**Comment by JestonBlu** [comment]
@fouslim @SwingBotScripts thank you both for the tip, i have committed and pushed the changes... ill push to CRAN this week.

**Comment by SwingBotScripts** [comment]
Great. Thanks!!
