### ISSUE TITLE
get_positions_options: Column `state` doesn't exist

### ISSUE THREAD

**Issue by fouslim** [JestonBlu/RobinHood#141]
Hi @JestonBlu.

I got a similar error as #139 when calling `get_positions_options`, this time column `state` is missing.
The fix I found was to modify line 67 of get_positions_options.R:
`options <- dplyr::inner_join(options, option_market_data, by = "option")`
to
`options <- dplyr::inner_join(options, option_market_data, by = c("option", "state"))`

thanks

**Comment by JestonBlu** [comment]
@fouslim thanks, ill push a fix shortly. It looks like the API changed to add some additional fields that are common and are being renamed when I join. I must have missed this one or it changed again after i fixed it. Ill push a fix to github tonight and a patch to CRAN in a week or so in case there are any other issues.
