### ISSUE TITLE
argument "mfa_code" is missing, with no default

### ISSUE THREAD

**Issue by jreeder3131** [JestonBlu/RobinHood#153]
I just updated to the Github version of the package this morning (login had broken on my CRAN installed version) and now I am getting an error that looks like it is related to MFA. 

I don't have MFA setup. Am I required to in order to continue using the package?

I prefer not to use MFA since I have some automated code running.

**Comment by cbengibson2** [comment]
The Robinhood API changed, and MFA is now required. I used the google authenticator app: I authenticated using the R package manually (by entering the MFA code provided by google authenticator), and then saved the RobinHood object for later use, e.g. `save(RH, file="RH.Rdata")`. It has worked for data collection for me (though I have been unable to place an order with the new version).

**Comment by JestonBlu** [comment]
I will test not being able to place an order. MFA is required at the moment for the github version. I will try to get both working again this weekend.

**Comment by jreeder3131** [comment]
Thanks, yeah my code relies on ability to place orders, so that would be appreciated.
