### ISSUE TITLE
Cannot place order

### ISSUE THREAD

**Issue by cbengibson2** [JestonBlu/RobinHood#156]
Hi All, 

I installed the new Github version this morning and was unable to place an order. The line in `RobinHood::api_orders` seems to be the issue:

```
    detail <- data.frame(account = RH$url.account_id, instrument = instrument_id, 
                         symbol = symbol, type = type, time_in_force = time_in_force, 
                         trigger = trigger, price = price, stop_price = stop_price, 
                         quantity = quantity, side = side, client_id = RH$api_client_id)
```

R is looking for `RH$api_client_id` but doesn't exist. If I run `RH$api_client_id<-RH$api_request.client_id` prior to placing the order, it works fine. 

HTH

**Comment by cbengibson2** [comment]
Ah, I see the problem -- I saved the RH authentication object before you updated the package, then used the older object to place the order. My bad! The new version works great. Thanks!

**Comment by ericvaughn11** [comment]
Thanks JestonBlu again for tackling the API issue so quickly. I have a related issue I thought I'd bring up here.

I'm running into an odd error with api_orders as well where I can seem to place a sell order, but get `Bad Request (HTTP 400).` when trying to place a buy order. I've tested this a few times and it rejects only buy orders. This is on 1.6.8. Any ideas?
