### ISSUE TITLE
HTTP 400 Bad Request on api_login

### ISSUE THREAD

**Issue by sneijder12** [JestonBlu/RobinHood#159]
Hi All - first of all - thanks to JestonBlu for quickly getting this 1.6.8 patch out for the recent API changes. Really appreciate it and anyone else who contributed to testing.

Apologize for re-opening this issue that was just closed, but I've been updating to the latest github versions (tried 1.6.7 yesterday, and 1.6.8 today) but am still getting 400 Bad Request in my api_login function. I turned on MFA and tried entering the code as a string and as a numeric but neither seems to work. I looked through the contents of the "dta" object and don't see any error codes or reasons (other than the 400 code). 

From running sessionInfo(), I see RobinHood version 1.6.8, httr version 1.4.3, jsonlite version 1.8.0, and magittr version 2.0.3 - if that helps. Any ideas on what could still be causing the issue? Could it be cookies or some other local data from the old Robinhood Package that is causing it?

**Comment by JosiahParry** [comment]
Just downloaded this package. Cannot log in with same error. My account does not have MFA. 

```
#> Error in RobinHood::api_login(username, password, mfa_code) : 
#>   Bad Request (HTTP 400).
```
