### ISSUE TITLE
404 on vignette getting started

### ISSUE THREAD

**Issue by dereckmezquita** [JestonBlu/RobinHood#162]
URL is: https://jestonblu.github.io/RobinHood/articles/getting_started.html

![Screenshot 2022-12-05 at 19 02 58](https://user-images.githubusercontent.com/44912288/205772664-f2733a99-c880-43e2-b26c-76aa3c7d8516.png)

**Comment by JestonBlu** [comment]
yeah i havent been able to figure out what is wrong... it compiles on my local but the workflow isnt working on gh. Will take help if anyone has ideas.
