### ISSUE TITLE
error due to order type

### ISSUE THREAD

**Issue by hrazif** [JestonBlu/RobinHood#61]
I think there is a typo in the place_order function. In the line below, "type" should be replaced with "limit". 

https://github.com/JestonBlu/RobinHood/blob/d278fd0f5fd8063104c561f72973ba70af464936/R/place_order.R#L35

**Comment by JestonBlu** [comment]
Thanks for the report. I have pushed a fix for this to the master branch and bumped the version... Ill plan on including this fix in the next release on CRAN.
