### ISSUE TITLE
add place_order_crypto, cancel_order_crypto, order_status_crypto

### ISSUE THREAD

**Issue by JestonBlu** [JestonBlu/RobinHood#63]

**Comment by otalbot94** [comment]
Hi JetsonBlu,

I tried downloading your function using the 3 separate methods:

1. install_github("https://github.com/JestonBlu/RobinHood")
2. devtools::install_github("jestonblu/RobinHood")
3. install.packages("RobinHood")

However, I still cannot location the function get_positions_crypto(). It comes up in the help tab as being within the Robinhood function as well, but it cannot be found when I run it. Can you assist with this?

Thank you for all of your help with this.

**Comment by JestonBlu** [comment]
I'll look at it tonight. The changes are only on the GitHub version right
now. Make sure you restart your r session.

**Comment by JestonBlu** [comment]
I did a simple uninstall of the package and then reinstalled it from github
via the command on the README.md
(devtools::install_github("jestonblu/RobinHood") and I was able to see
get_positions_crypto and confirm that it loaded and ran. I would suggest
uninstalling the current version you have installed and then closing your R
session... reopen and try the install command again. Hope that helps.

**Comment by JestonBlu** [comment]
Added several functions for crypto currency #66

**Comment by rrpaleja** [comment]
Thanks for this @JestonBlu 
Just some findings:
 - get_quote_crypto(RH, symbol = "DOGE") works perfectly
- x = place_order_crypto(RH,
                       symbol        = "DOGE",
                       type          = "market",
                       time_in_force = "gfd",
                       price         = .002,
                       quantity      = 400,
                       side          = "buy") does not..

I'm seeing "Method \"POST\" not allowed".. Not sure if I'm doing something incorrectly. Haven't looked into it more, but if you get a chance, that would be great!!

**Comment by JestonBlu** [comment]
@rrpaleja Thanks, it looks like I had a typo in the api url when i coded it. I just fixed it and pushed to master. My plan is to push a maintenance release to CRAN this weekend. Feel free to use the github version in the mean time. 3ae8720

**Comment by rrpaleja** [comment]
@JestonBlu You are a beast! Works :)
