### ISSUE TITLE
Security and Implementation with Shiny

### ISSUE THREAD

**Issue by Sbirch556** [JestonBlu/RobinHood#75]
Is storing RobinHood Oauth2 tokens within a Shiny app a viable and secure option? 

Say for example a user were to login to Shiny Server Pro or R Studio Connect which I believe uses a layer of authentication using an encrypted cookie for each user. From there a Shiny app provides an additional login page with a password input for password and text input for a username.

From there the users Oauth2 token was then stored in a reactive variable within the R Shiny app, so the token can be used and reused as the user navigates about the app. Would this token need to be hashed within this reactive variable?

This might be a better question for Oauth or Shiny...but asking here for now.

**Comment by JestonBlu** [comment]
Hey, yeah I'm not really the best person to answer this. Security isn't my background at all. What you are proposing sounds about right to me, but im not sure about the need for a hashed token. I would be interested to hear what you find out.
