### ISSUE TITLE
Error in UseMethod("tbl_vars")

### ISSUE THREAD

**Issue by stevencurrie** [JestonBlu/RobinHood#76]
Full error: Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "NULL"

RobinHood installed okay.  Library loads fine.  Error above occurs when connecting to robinhood.  On this line
RH = RobinHood(username = "myusename", password = "mypassword")

I tried R 3.6.1, R 3.5.1, and R 3.4.4.  I used both install.packages("RobinHood") and devtools::install_github("jestonblu/RobinHood") in every case.  Tried on Windows 10 1909 and Ubuntu 18.04.3.  Same error on both OSes and in every version of R I tried.

**Comment by stevencurrie** [comment]
Further testing showed username needed to be email address.  Closing.

**Comment by Mike-TT** [comment]
Used email and am getting the error of:
Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "NULL"
