### ISSUE TITLE
Is there a way to get more than 100 rows from the get_order_history?

### ISSUE THREAD

**Issue by ptaal** [JestonBlu/RobinHood#77]

**Comment by JestonBlu** [comment]
I wasnt aware of this limitation, ill look into it and let you know what I find.

**Comment by JestonBlu** [comment]
@ptaal Ive put in a quick fix more or less to allow you to expand beyond the last 100 lines. The `page_size` parameter is now set as a default to 1000, I did not test the limits of how much you can pull back, but I was able to get all of my RobinHood history.

I know this is not really preferred solution, I will make a note to keep looking at the API about this. Feel free to reopen the issue if you find problems.

I have pushed the update to the github version, im working on another open issue at the moment and when I resolve that I will push to CRAN, thinking sometime mid next week.
