### ISSUE TITLE
Crypto Order Quantity too small

### ISSUE THREAD

**Issue by sanseveroj** [JestonBlu/RobinHood#78]
When trying to execute crypto trades I often get an error saying that the quantity for the order is too small. I'm not sure if this is something that can be fixed or if it is something on the RobinHood end which we won't be able to fix. 

for example if I wanted to trade 25$ worth of Bitcoin right now that would be about .0026 BTC which I believe the system errors out past 2 decimal places from some rudimentary testing.

**Comment by JestonBlu** [comment]
Thanks for letting me know, ill investigate and let you know what I find.

**Comment by JestonBlu** [comment]
@sanseveroj I have pushed a fix for this. I was able to buy a 0.0001 fractional share of BTC with no problem. Sorry for taking so long to get this fixed. Let me know if you have any other issues.

Ill probably push to CRAN soon. For now its published on the github version.
