### ISSUE TITLE
get_positions(RH) error Error in handle_url

### ISSUE THREAD

**Issue by abheek24** [JestonBlu/RobinHood#82]
While implementing get_positions(RH) I ma getting this error. Could you help?

Error in handle_url(handle, url, ...) : 
  Must specify at least one of url or handle

**Comment by JestonBlu** [comment]
Looks like the api has changed, i will look at this quickly and push a fix, thanks for reporting it.

**Comment by JestonBlu** [comment]
So it looks like they changed the positions url and it no longer available through that call. I spent some time trying to find it last night but I didn't see it. I can see in the API how they are getting things like quotes but I'm not able to get the instrument IDs of the portfolio yet. I will spend some time investigating today.

**Comment by abheek24** [comment]
Thanks for looking into it. Appreciate it. Let me know if you are able to figure out.

**Comment by deanmayne** [comment]
I did some investigating myself to the api changes from the site upgrade and have been setting the following before calling get_positions() as a workaround:

RH$url.positions = "https://api.robinhood.com/positions/"

I hope this helps lead to a solve !

**Comment by JestonBlu** [comment]
Thanks, ill test this tonight

**Comment by JestonBlu** [comment]
@deanmayne  That was kind of a no brainer, thanks for posting, i have pushed a fix. Will send to CRAN this weekend.
