### ISSUE TITLE
Time Zone in get_historicals()

### ISSUE THREAD

**Issue by tianqinglong** [JestonBlu/RobinHood#86]
Hi JestonBlu,

Thanks for your work!

I ran the following lines and it seems that the time in the output of get_historicals() is ahead of my local time. I think it would be better to show the time based on the user's time zone.

Thanks

```r
> Sys.time()
[1] "2020-04-16 10:37:47 CDT"
> get_historicals(RH, 'CAT', interval = '30minute', span = 'day')
            begins_at open_price close_price high_price low_price volume session interpolated
1 2020-04-16 13:30:00    111.835    110.1938    112.155    110.10 121485     reg        FALSE
2 2020-04-16 14:00:00    110.190    110.1100    110.420    108.88 136195     reg        FALSE
3 2020-04-16 14:30:00    110.100    110.9050    111.190    109.76 106401     reg        FALSE
4 2020-04-16 15:00:00    110.940    111.1250    111.735    110.80  73153     reg        FALSE
```

**Comment by tianqinglong** [comment]
> Sys.time()
[1] "2020-04-16 11:09:13 CDT"
> Sys.timezone()
[1] "America/Chicago"
> get_market_hours(RH)
                           name acronym     city             website   timezone            opens_at           closes_at   extended_opens_at  extended_closes_at is_open       date
1                    IEX Market     IEX New York  www.iextrading.com US/Eastern 2020-04-16 13:30:00 2020-04-16 20:00:00 2020-04-16 13:00:00 2020-04-16 22:00:00    TRUE 2020-04-16
2                   Otc Markets    OTCM New York  www.otcmarkets.com US/Eastern 2020-04-16 13:30:00 2020-04-16 20:00:00 2020-04-16 13:00:00 2020-04-16 22:00:00    TRUE 2020-04-16
3                  NYSE Mkt Llc    AMEX New York        www.nyse.com US/Eastern 2020-04-16 13:30:00 2020-04-16 20:00:00 2020-04-16 13:00:00 2020-04-16 22:00:00    TRUE 2020-04-16
4                     NYSE Arca    NYSE New York        www.nyse.com US/Eastern 2020-04-16 13:30:00 2020-04-16 20:00:00 2020-04-16 13:00:00 2020-04-16 22:00:00    TRUE 2020-04-16
5 New York Stock Exchange, Inc.    NYSE New York        www.nyse.com US/Eastern 2020-04-16 13:30:00 2020-04-16 20:00:00 2020-04-16 13:00:00 2020-04-16 22:00:00    TRUE 2020-04-16
6          NASDAQ - All Markets  NASDAQ New York      www.nasdaq.com US/Eastern 2020-04-16 13:30:00 2020-04-16 20:00:00 2020-04-16 13:00:00 2020-04-16 22:00:00    TRUE 2020-04-16
7                 BATS Exchange    BATS New York www.batstrading.com US/Eastern 2020-04-16 13:30:00 2020-04-16 20:00:00 2020-04-16 13:00:00 2020-04-16 22:00:00    TRUE 2020-04-16

**Comment by JestonBlu** [comment]
@tianqinglong 

I have adjusted the function so that it returns times in your local timezone by default. The timezone listed in the return will also reflect that same timezone. You can also supply a different timezone to convert the time to something other than local. 

```r
get_market_hours(RH, tz = "America/Chicago")
get_market_hours(RH, tz = "America/New_York")
```

**Comment by JestonBlu** [comment]
I will implement a similar change to `get_historicals()`

**Comment by JestonBlu** [comment]
Going to keep open until i fix the `get_historicals()` function, hopefully tonight

**Comment by JestonBlu** [comment]
added same functionality to `get_historicals()`
