### ISSUE TITLE
get_historicals() questions and error message

### ISSUE THREAD

**Issue by 3SMMZRjWgS** [JestonBlu/RobinHood#88]
@JestonBlu 

I'm back with some questions on `get_historicals()`

(1) For the date/time stamps under begin_at column generated by `get_historicals()`, can I assume they are UTC based? They usually start at 14:00 PM every day, which is about 9:00AM Eastern?

(2) Is the maximum historicals obtainable by this function trailing one year on a daily interval? In other words, there's no way to obtain full historicals of a ticker longer than a year?

(3) I was trying out different combinations of the settings in get_historicals() and it appears that every combination works except when it's `interval = "hour"` and `span = "year"`. I've tried this setting combination with several different tickers and got the same error message blow. I was wondering if you could please take a look? Or perhaps Robinhood only provides hourly interval historicals for up to one trailing month?
```

> y <- get_historicals(RH = RH, symbol = "MSFT", interval = "hour", span = "year")
Error: Can't subset columns that don't exist.
x The column `open_price` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/vctrs_error_subscript_oob>
Can't subset columns that don't exist.
x The column `open_price` doesn't exist.
Backtrace:
  1. RobinHood::get_historicals(...)
 32. vctrs:::stop_subscript_oob(...)
 33. vctrs:::stop_subscript(...)
Run `rlang::last_trace()` to see the full context.
```

FYI: the above was produced using version 1.3.1 of the package on Github.

**Comment by JestonBlu** [comment]
So for 1) the github version has changed the timezone to be your local timezone, you can also input a different timezone if you want to convert it to something else. Yes, the default was UTC originally and someone else requested that timezone flexibility be added.

For 2) Ive tested a few options. Basically the limitations are similar to the RH websiste. You can pull hourly up to a year, after that you have to go to at least a daily aggregation. The most I was able to do was daily going back 5 years. Your options for multiple years, like on the website are 1 year and 5 years, but the chart on the website will show weekly, so you are able to actually pull daily through the api.

I suppose one could argue that hourly data going back that far has limited usefulness. Let me know if this doesn't clear things up.
