### ISSUE TITLE
mod_json(dta, "fromJSON") returns "Invalid Authorization header"

### ISSUE THREAD

**Issue by tchaithonov** [JestonBlu/RobinHood#90]
Hi Jeston,

I was setting up my connection to RobinHood, and happened to run into this issue when trying to open up the hood:

1) Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "NULL" when putting in username and password
2) further looked into `accounts <- RobinHood:::api_accounts(RH)`, and I got the message in 1).

Looking back at api_logins, both access and refresh tokens are empty.

So, I can't login.  

Btw, it looks like there is also a problem if there are special characters in the password.  Any ideas?  Thanks.

**Comment by JestonBlu** [comment]
This has been reported before. Make sure you have your username set to your email address. Others have reported error messages when they just put in the username and not the full address. Let me know if this still doesn't work.

**Comment by JestonBlu** [comment]
Also you can't have special characters in your password currently. I will create a separate issue to try and address that.
