### ISSUE TITLE
Error when using get_order_history_crypto()

### ISSUE THREAD

**Issue by rlusch** [JestonBlu/RobinHood#93]
I recieve the following error and traceback message when trying to run the function:

```
Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 26, 27
6.
stop(gettextf("arguments imply differing number of rows: %s", paste(unique(nrows), collapse = ", ")), domain = NA)
5.
data.frame(..., check.names = FALSE)
4.
cbind(deparse.level, ...)
3.
cbind(dta, executions)
2.
api_orders_crypto(RH, action = "history")
1.
get_order_history_crypto(RH)
```
Using R 4.0.0 64bit via RStudio.

**Comment by JestonBlu** [comment]
Can you try the GitHub version?

**Comment by JestonBlu** [comment]
I've pushed a new version to cran try upgrading and let me know if you still see the issue.

**Comment by JestonBlu** [comment]
ive been able to run this without issue and ive heard nothing else so ill assume its working fine
