### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by Chandrak1907** [JestonBlu/RobinHood#97]
How to resolve this error?

```
RH = RobinHood(username = 'ux', password ='***')
Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "NULL"
```

**Comment by JestonBlu** [comment]
@Chandrak1907  Do you have special characters in your password? This is a known issue that doesnt work right now. I have an open issue to resolve this.

**Comment by Chandrak1907** [comment]
Yes. Do I need to change my password, before using this?

**Comment by JestonBlu** [comment]
Yes I would recommend changing it and test again to verify that is the
actual issue. I believe it is. Like I said im working on fixing this, but I
havent pushed a fix yet.
