### ISSUE TITLE
Keep getting error in useMethod("tbl_vars")

### ISSUE THREAD

**Issue by bora19** [JestonBlu/RobinHood#99]
When trying to connect via the following command

RH = RobinHood(username = "MyUsername", password = "MyPassword")

I keep getting the following error code

Error in UseMethod("tbl_vars") : 
  no applicable method for 'tbl_vars' applied to an object of class "NULL"

Im using the correct username and password.  NOTE: my password includes special characters not sure if it matters or not

**Comment by jsraadt** [comment]
I had the same error, changed my password to no special characters, and the error went away.

**Comment by bora19** [comment]
Yeah changing the password to not include special characters worked but made my password less secure.  We should not be changing password sounds like a bug

**Comment by JestonBlu** [comment]
This is a known issue that I'm working on. I keep getting issues created for this so I will pin this going forward until I get it resolved.

**Comment by JestonBlu** [comment]
#95

**Comment by moosedoc011** [comment]
Attempted to simplify the password as outlined above -- still receiving the same error message. Is it possible this it related to 2FA?

**Comment by JestonBlu** [comment]
@moosedoc011  Maybe, i do not have any features related to 2FA, i will include that as a separate feature but i will prioritize it

**Comment by kfquach** [comment]
Just wanted to comment that I'm having this same issue as well.

**Comment by JestonBlu** [comment]
I have been working this, but i havent been able to find a solution as of yet. I have posted a [stackoverflow](https://stackoverflow.com/questions/63819558/how-to-store-a-special-character-in-a-string-in-r) looking for help on this one, but so far no takers. Anyone interested in proposing a solution would appreciated.

**Comment by JestonBlu** [comment]
After working through this issue on [stackoverflow](https://stackoverflow.com/questions/63819558/how-to-store-a-special-character-in-a-string-in-r) i have posted a fix below. I will add the commentary in the main README for future reference.


```R
library(RobinHood)

# If the true password is: abc\def

# The following inputs will all work
rh <- RobinHood("username", pwd = r"(abc\def)")
rh <- RobinHood("username", pwd = "abc\\def")
rh <- RobinHood("username", pwd = "abc%5Cdef")

```

**Comment by e-arslan** [comment]
still getting this problem and there is no special character in the password.



R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

**Comment by JestonBlu** [comment]
are you inputting your email as your username?

**Comment by JestonBlu** [comment]
@e-arslan do you have 2-step authentication enabled on your account? I have not implemented that feature yet but agree its time. I will start looking into it.

**Comment by wittec** [comment]
I'm getting this same problem. I have a special character in the password. I am using email address as username. I've tried the proposed fixes from November 7, but they aren't working for me. I have mfa disabled on account.

**Comment by JestonBlu** [comment]
@wittec what package version are you on?

**Comment by wittec** [comment]
I tried the GitHub and the Cran version, but no luck.

Chris Witte
Research Scientist
Agricultural and Biosystems Engineering
Iowa State University
4306B Elings Hall
Ames, IA 50011
573-864-6629

________________________________

**Comment by JestonBlu** [comment]
@wittec do you have multi-factor authentication enabled?

**Comment by wittec** [comment]
Nope

Chris Witte
Research Scientist
Agricultural and Biosystems Engineering
Iowa State University
4306B Elings Hall
Ames, IA 50011
573-864-6629

________________________________

**Comment by JestonBlu** [comment]
I just tried it both with and without MFA and it worked fine for me. My password also contains special characters. Could you maybe try changing your password and using some different special characters to see if that works? I have continued to receive a few inquiries about this, but i havent been able to find anymore issues related to the code. I keep coming back to the password itself.

**Comment by wittec** [comment]
Ok, a password change was going to be my last effort. Thanks for your reply!

Chris Witte
Research Scientist
Agricultural and Biosystems Engineering
Iowa State University
4306B Elings Hall
Ames, IA 50011
573-864-6629

________________________________

**Comment by wittec** [comment]
> I just tried it both with and without MFA and it worked fine for me. My password also contains special characters. Could you maybe try changing your password and using some different special characters to see if that works? I have continued to receive a few inquiries about this, but i havent been able to find anymore issues related to the code. I keep coming back to the password itself.

I changed my password and it is working now! Thank you!

**Comment by JestonBlu** [comment]
That's great. Id like to know what went wrong with your last password.
Would you mind sharing what special characters you used in your password
that didn't work and what character position they were in? I'll try to work
a fix if there is something I can do.

**Comment by wittec** [comment]
it was a "#" character. It was in the middle of the password.

**Comment by JestonBlu** [comment]
Thanks. I'll look into it and hopefully find a solution.

**Comment by JanLauGe** [comment]
Hi! First of all, thank you for making this package available. Great work!

I am running into issues with this as well. After ironing out details with password and MFA, my error is now slightly different to the ones described above but also a `table_vars()` error:
```
RH <- RobinHood(username="me@email.com", password="nospecialcharacters")
>  Error in UseMethod("tbl_vars") : 
>  no applicable method for 'tbl_vars' applied to an object of class "logical"
```

Digging in a bit further, it looks like authentication works fine but my response json does not contain margin balances
```
dta$margin_balances
[1] NA
```

Any ideas how to get around this?

**Comment by SwingBotScripts** [comment]
@JanLauGe 

I am having the same issues after months of successful access, and just posted on thread https://github.com/JestonBlu/RobinHood/issues/124 .

Thinking about what changed for me this week...I downgraded my account from Instant Settlement to Cash in order to day trade with a smaller balance. I just read that you were having issues with margin balances being NA. This would make sense if margin trading is disabled, which is a feature of the Cash account. You say you had to supply "fake data" for the margin_balances to resolve the issue. Can you provide more insight on how you did this? I want to try the same.

Thanks!

**Comment by JanLauGe** [comment]
Hey! Coming back to this after some time.
I just put in a PR that fixes this for me. Root cause is a small if statement that seems buggy.
PR: https://github.com/JestonBlu/RobinHood/pull/146
